server:
  port: 18992

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${restaurant.db.username}
    password: ${restaurant.db.password}
    url: ${restaurant.db.url}
  flyway:
    enabled: true
    user: ${restaurant.db.username}
    password: ${restaurant.db.password}
    url: ${restaurant.db.url}
    schemas: ${restaurant.db.schema}
    placeholders.restaName: ${spring.application.name}
